### ISSUE TITLE
Default build settings not working for me. Giving various undefined issues.

### ISSUE THREAD

**Issue by SamuelFrost** [bennypowers/rollup-plugin-modulepreload#6]
I imagine I'm just not setting it up right, but starting simply first, I'm getting some undefined messages when I try to build with any of the standard setups in the readme.
(in plugins)
```
modulepreload({
  index: 'index.html',
  shouldPreload: ({ facadeModuleId }) =>
    fs.promises.readFile(facadeModuleId, 'utf-8')
      .then(file => file.includes('INCLUDE THIS CHUNK')),
})
```
result:
```
[!] (plugin modulepreload) ReferenceError: fs is not defined
ReferenceError: fs is not defined
    at shouldPreload (.../rollup.config.js:85:12)
```
(in plugins)
```
modulepreload({
  index: 'index.html',
})
```
result:
```
[!] (plugin modulepreload) TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at defaultShouldPreload (.../node_modules/rollup-plugin-modulepreload/index.js:23:33)
```

After adding:
`import fs from 'fs';`
at the top of rollup config

Getting this:
```
[!] (plugin modulepreload) TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received null
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at open (internal/fs/promises.js:306:10)
```

Here's my project for reference. I've created the modulepreload branch for tackling this problem and pushed code producing the build error.
https://github.com/SamuelFrost/portfolio/tree/modulepreload/portfolio-application

**Comment by bennypowers** [comment]
Try with [v1.2.3](https://npm.im/rollup-plugin-modulepreload). If you customize `shouldPreload`, please consult the [updated README](https://www.npmjs.com/package/rollup-plugin-modulepreload#options)

Please reopen if this doesn't fix.
